spring:
  datasource:
    url: jdbc:postgresql://localhost:54422/silk-payment
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:54422/silk-payment
    schemas: public
    user: postgres
    password: postgres
    out-of-order: true
    validate-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 54711
    username: guest
    password: guest



  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

customer-service:
  feign:
    url: http://localhost:8080
