services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=silk-payment'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '54422:5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
      - '54711:5672'
      - '15672:15672'
