spring:
  datasource:
    url: jdbc:postgresql://localhost:54422/silk-payment
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: localhost
    port: 54711
    username: guest
    password: guest

  main:
    allow-bean-definition-overriding: true

server:
  port: 8081

customer-service:
  feign:
    url: http://localhost:8080


ribbon:
  enabled: false
